In [1]:
import numpy as np

## numpy 의 행렬에 관한 참고 문서
- https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.matrix.html
- https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.det.html
- https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.solve.html

## 행렬 만들기
- ```numpy.matrix``` : 수학적인 의미에 가깝게 표기해 준다.

In [2]:
A = np.matrix('1.1, 1.2, 1.3, 1.4; 2.1, 2.2, 2.3, 2.4; 3.1, 3.2, 3.3, 3.4; 4.1, 4.2, 4.3, 4.4')
x = np.matrix('1;2;3;4')
print(A)
print('-------------')
print(x)

[[1.1 1.2 1.3 1.4]
 [2.1 2.2 2.3 2.4]
 [3.1 3.2 3.3 3.4]
 [4.1 4.2 4.3 4.4]]
-------------
[[1]
 [2]
 [3]
 [4]]


## 행렬 만들기
- ```numpy.array``` : 사용하기 편하게 표기해 준다.

In [3]:
A = np.array([[1.1, 1.2, 1.3, 1.4], [2.1, 2.2, 2.3, 2.4], [3.1, 3.2, 3.3, 3.4], [4.1, 4.2, 4.3, 4.4]])
x = np.array([1,2,3,4])
print(A)
print('-------------')
print(x)

[[1.1 1.2 1.3 1.4]
 [2.1 2.2 2.3 2.4]
 [3.1 3.2 3.3 3.4]
 [4.1 4.2 4.3 4.4]]
-------------
[1 2 3 4]


## 행렬 벡터 곱 1 (Matrix-Vector Multiplication)
일반적인 행렬 벡터 곱셈
\begin{equation}
\begin{bmatrix}
1 & 2 & 2 & 0 \\
3 & 2 & 1 & 0 \\
0 & 0 & 2 & 1 \\
0 & 3 & 1 & 3
\end{bmatrix}
\begin{bmatrix}
1\\2\\2\\1
\end{bmatrix}=?
\end{equation}

In [4]:
A = np.matrix('1, 2, 2, 0; 3, 2, 1, 0; 0, 0, 2, 1; 0, 3, 1, 3')
x = np.matrix('1;2;2;1')
b = np.zeros((4,1))
n = 4
for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO 1
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[[ 9.]
 [ 9.]
 [ 5.]
 [11.]]


In [5]:
A = np.array([[1, 2, 2, 0], [3, 2, 1, 0], [0, 0, 2, 1], [0, 3, 1, 3]])
x = np.array([1,2,2,1])
b = np.array([0,0,0,0])
n = 4
for i in range(0, n):
    val = 0.0
    for j in range(0,n):
        # TODO 2
        val += A[i,j] * x[j]
    b[i] = val
print(b)

[ 9  9  5 11]


## 행렬 벡터 곱 2 (Matrix-Vector Multiplication)
곱연산을 ```numpy```를 사용해 계산합니다.
\begin{equation}
\begin{bmatrix}
1 & 2 & 2 & 0 \\
3 & 2 & 1 & 0 \\
0 & 0 & 2 & 1 \\
0 & 3 & 1 & 3
\end{bmatrix}
\begin{bmatrix}
1\\2\\2\\1
\end{bmatrix}=?
\end{equation}

In [6]:
# np.matrix 를 사용하면 행렬 벡터 곱을 직관석인 수식으로 구할 수 있습니다.
A = np.matrix('1, 2, 2, 0; 3, 2, 1, 0; 0, 0, 2, 1; 0, 3, 1, 3')
x = np.matrix('1;2;3;4')
print(A)
print('-------------')
print(x)
print('-------------')

# TODO 3
b = A*x
print(b)

[[1 2 2 0]
 [3 2 1 0]
 [0 0 2 1]
 [0 3 1 3]]
-------------
[[1]
 [2]
 [3]
 [4]]
-------------
[[11]
 [10]
 [10]
 [21]]


In [7]:
# np.array 의 경우 numpy 의 matmul 을 사용해야 곱연산을 정상적으로 처리 할 수 있습니다.
A = np.array([[1, 2, 2, 0], [3, 2, 1, 0], [0, 0, 2, 1], [0, 3, 1, 3]])
x = np.array([1,2,2,1])
print(A)
print('-------------')
print(x)
print('-------------')

b = np.array([0,0,0,0])
b = np.dot(A,x)
print(b)
print('-------------')

b = np.matmul(A,x)
print(b)

[[1 2 2 0]
 [3 2 1 0]
 [0 0 2 1]
 [0 3 1 3]]
-------------
[1 2 2 1]
-------------
[ 9  9  5 11]
-------------
[ 9  9  5 11]


In [8]:
# np.array 를 np.matrix 처럼 직관적으로 곱연산을 하면 정상적인 벡터 결과값이 나오지 않습니다.
A = np.array([[1, 2, 2, 0], [3, 2, 1, 0], [0, 0, 2, 1], [0, 3, 1, 3]])
x = np.array([1,2,2,1])

In [9]:
# 결과값이 벡터가 나와야 하는데 행렬이 나옵니다.
A*x

array([[1, 4, 4, 0],
       [3, 4, 2, 0],
       [0, 0, 4, 1],
       [0, 6, 2, 3]])

In [10]:
np.dot(A,x)

array([ 9,  9,  5, 11])

In [11]:
np.dot(x,A)

array([7, 9, 9, 5])