In [1]:
import numpy as np

## 선형 방정식 풀기 (Soution of the Linear System)
1. 다음 선형 방정식의 해를 찾아봅니다.
1. `numpy` 를 사용해서 선형 방정식의 답 x 를 찾아봅니다.

\begin{equation}
\begin{bmatrix}
1 & 2 & 2 & 0 \\
3 & 2 & 1 & 0 \\
0 & 0 & 2 & 1 \\
0 & 3 & 1 & 3
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
11\\10\\10\\21
\end{bmatrix}
\end{equation}

In [2]:
A = np.matrix('1, 2, 2, 0; 3, 2, 1, 0; 0, 0, 2, 1; 0, 3, 1, 3')
b = np.matrix('11;10;10;21')

In [3]:
# numpy 의 함수를 통해 행렬식 (determinant) 확인
np.linalg.det(A)

-35.00000000000001

In [4]:
x = np.linalg.solve(A, b)
x

matrix([[1.],
        [2.],
        [3.],
        [4.]])

In [5]:
A = np.array([[1, 2, 2, 0], [3, 2, 1, 0], [0, 0, 2, 1], [0, 3, 1, 3]])
b = np.array([11,10,10,21])

In [6]:
# determinant 구해주는 함수
np.linalg.det(A)

-35.00000000000001

In [7]:
# numpy 안에 있는 linear algebra 선형 방정식 풀이 함수로 결과 확인
x = np.linalg.solve(A,b)
x

array([1., 2., 3., 4.])

## 선형 방정식 풀기 2 (Not invertible Lineary System)
Determinant 가 0 인 방정식

\begin{align}
x_1 + x_2 &= 2\\
2x_1 + 2x_2 &= 3
\end{align}
행렬로 표현하면, 
\begin{equation}
\begin{bmatrix}
1 & 1 \\
2 & 2 
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2
\end{bmatrix}=
\begin{bmatrix}
2\\3
\end{bmatrix}
\end{equation}

In [8]:
A = np.matrix('1, 1; 2, 2')
b = np.matrix('2;3')
# determinant 가 0 이다
np.linalg.det(A)

0.0

In [9]:
x = np.linalg.solve(A, b)

LinAlgError: Singular matrix

#### 행렬 A 는 행렬식(determinant)이 0 인 행렬이라서 solve 를 하지 못해 오류가 발생합니다. (Singular matrix = 특이 행렬)

---

## 선형 방정식 풀기 3 (Soution of the Linear System)
야코비안 방법을 사용해 선형 방정식을 풀고 x 를 구합니다.
\begin{equation}
\begin{bmatrix}
10 & 4 & 2 & 0 \\
9 & 15 & 0 & 0 \\
4 & 0 & 12 & 4 \\
6 & 1 & 8 & 13
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4
\end{bmatrix}=
\begin{bmatrix}
15\\19\\26\\44
\end{bmatrix}
\end{equation}

In [10]:
A = np.matrix('10, 4, 2, 0; 9, 15, 0, 0; 4, 0, 12, 4; 6, 1, 8, 13')
b = np.matrix('15;19;26;44')

In [11]:
# np.diag : 대각행렬 생성
D = np.diag(np.diag(A))
R = A - D

In [12]:
invD = np.matrix(np.diag(1 / np.diag(A)))
invD

matrix([[0.1       , 0.        , 0.        , 0.        ],
        [0.        , 0.06666667, 0.        , 0.        ],
        [0.        , 0.        , 0.08333333, 0.        ],
        [0.        , 0.        , 0.        , 0.07692308]])

- $x^{(k+1)} = D^{-1} (b - Rx^{(k)})$

In [13]:
MaxIter = 10
x0 = np.matrix('1;1;1;1')
for it in range(MaxIter):
    # TODO 1
    x1 = invD * (b - R * x0)
    x0 = x1

In [14]:
x0

matrix([[1.01603595],
        [0.65583037],
        [1.09652471],
        [2.18615955]])

In [15]:
# 결과 비교
np.linalg.solve(A,b)

matrix([[1.01814882],
        [0.65577737],
        [1.09770115],
        [2.18874773]])